remote_theme: pages-themes/tactile@v0.2.0
title: Blog
description: Reflective Learning

utterances:
  repo: "Sterling-Cooper/sterling-cooper.github.io"
  issue-term: "comment"
  label: "comment"
  theme: "github-light"
